# Generated by Django 5.1.1 on 2024-09-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
    ]
