# Generated by Django 5.1.1 on 2024-09-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_contributer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone'),
        ),
    ]
