# Generated by Django 5.1.1 on 2024-09-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_contributer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ghost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
            ],
            options={
                'verbose_name': 'Ghost',
                'verbose_name_plural': 'Ghosts',
            },
        ),
    ]
