# Generated by Django 5.1.1 on 2024-09-20 14:37

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_contributer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Stack',
                'verbose_name_plural': 'Stacks',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('image', models.ImageField(upload_to='projects/images/<django.db.models.fields.CharField>', verbose_name='image')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='video url')),
                ('production_url', models.URLField(blank=True, null=True, verbose_name='production url')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.category', verbose_name='Category')),
                ('contributers', models.ManyToManyField(blank=True, null=True, to='account.contributer', verbose_name='contributers')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ownerinfo', verbose_name='owner')),
                ('stacks', models.ManyToManyField(to='projects.stack', verbose_name='stacks')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='projects/images/None/features/<django.db.models.fields.CharField>', verbose_name='image')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='video url')),
                ('production_url', models.URLField(blank=True, null=True, verbose_name='Production url')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Project feature',
                'verbose_name_plural': 'Project features',
                'ordering': ['-created_at'],
            },
        ),
    ]
